# cluster_role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: <YOUR-CLUSTER-ROLE-NAME> # full-pod-access
rules:
  - apiGroups: ["*"]
    resources: ["*"] # para acceder a todos los recursos "*"
    verbs: ["get", "watch", "list", "create", "delete"]
