# cluster_role_binding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  <YOUR-CLUSTER-ROLE-BINDING-NAME> # full-pod-access-binding
subjects:
  - kind: User
    name: <YOUR-USER-NORMAL OR USER FROM SERVICE ACCOUNT> # user del config de KUBECTL o del service account
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: <YOUR-CLUSTER-ROLE-NAME> # full-pod-access # enlazando al cluster-role.yaml
  apiGroup: rbac.authorization.k8s.io
