apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: YOUR-NAME-PVC # (important) el nombre debe coincidir con el del PV.
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
