# example filename: my-user-admin-service-account.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name:  <YOUR-USERNAME-FROM-SERVICE-ACCOUNT> # my-user-admin # <user-admin-name>
  # namespace: kubernetes-dashboard
